const listProducts = [{
    id:1,
    title:'Remera',
    srcImage: 'path',
    altImage: 'alt',
    description: 'Descripcion',
    talle: 'XL',
    price: 1500,
    stock: 3,
},
{
    id:2,
    title:'Pantalon',
    srcImage: 'path',
    altImage: 'alt',
    description: 'Descripcion',
    talle: 'L',
    price: 2500,
    stock: 5,
},
{
    id:3,
    title:'Zapatilla',
    srcImage: 'path',
    altImage: 'alt',
    description: 'Descripcion',
    talle: '40',
    price: 5500,
    stock: 7,
},
{
    id:4,
    title:'Camisa',
    srcImage: 'path',
    altImage: 'alt',
    description: 'Descripcion',
    talle: 'XXL',
    price: 3000,
    stock: 5,
},
{
    id:5,
    title:'Blusa',
    srcImage: 'path',
    altImage: 'alt',
    description: 'Descripcion',
    talle: 'M',
    price: 1500,
    stock: 4,
}];

export default listProducts;
